[package]
name = "prepona"
version = "0.0.1"
authors = ["m.amin.rayej <m.amin.rayej@gmail.com>"]
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.22.0"
num-traits = "0.2.12"

[dev-dependencies]
rand = "0.7.3"